<?php require __DIR__ .  "/layourt/header.php";?>


<h2> Contact Form </h2>

<form action="/contact" method="POST">

    <label for="name"> Name </label>
    <input type="text" name="name" id="name">
    <label for="vorname"> Vorname </label>
    <label for="Vorname"></label>
    <input type="text" name="Vorname" id="Vorname">
    <label for="message"> Message</label>
    <input type="text" name="message" id="name">
    <button type="submit" name="submit" > Submit <button>


</form>


<?php require __DIR__ .  "/layourt/footer.php";?>